### ISSUE TITLE
建议做一个可以拥有多个后缀的插件

### ISSUE THREAD

**Issue by UPchonger** [IdeaMC/Idea#1]
前置插件：GM权限组,PAPI
主要实现功能：玩家可以拥有多个后缀，可以自由切换
需要支持的：颜色代码(&)/占位符(玩家名字)
举栗子：玩家同时拥有两个后缀（&b[史无前例的大fw]/&a[疯狗]）
当前玩家用的是&b[史无前例的大fw]可以通过什么指令打开称号仓库选择切换&a[疯狗]
然后玩家通过自己用op权限执行命令/manuaddv %player%(我忘了玩家名字占位符是啥了) suffix <要设置的后缀（&a[疯狗]）>
然后玩家的后缀变成&a[疯狗]
插件的命令以及权限：/suffix-open(打开称号仓库) 权限节点setsuffix.open(默认直接给玩家)
/suffix-give <玩家> <后缀>（给玩家后缀）权限节点setsuffix.give(默认给op权限的玩家)

**Comment by xiantiao233** [comment]
服务器核心，版本

**Comment by UPchonger** [comment]
paper1.12.2(waterfull的子服，这个应该没关系吧)

**Comment by xiantiao233** [comment]
> paper1.12.2（waterfull的子服，这个应该没关系吧）

好的

**Comment by suxiaolinya** [comment]
https://github.com/IdeaMC/TitlePlugin

**Comment by xiantiao233** [comment]
@UPchonger  这个插件已被制作
接下来的问题请到
`https://github.com/IdeaMC/TitlePlugin`
提出
