### ISSUE TITLE
1.20.x 不同权限不同出生点

### ISSUE THREAD

**Issue by MoXiaoYan7612** [IdeaMC/Idea#5]
# 不同权限不同出生点
## 配置文件设置某权限的出生点

# 信息
服务器核心 `all`  
服务器版本 `1.20.x`  
适配Geyser `false`  

# 具体想法
配置文件中可以设置某一权限的出生点

例如权限组中拥有"admin"这个权限则会在world这个世界里面重生在0 0 0坐标上
而有"player"权限的玩家会在world世界里面重生在100 100 100上

感谢大佬有时间制作此插件

**Comment by xiantiao233** [comment]
服务器核心将为spigot

**Comment by xiantiao233** [comment]
@MoXiaoYan7612 
还需要什么吗
![image](https://github.com/IdeaMC/Idea/assets/112249833/9665c33e-00c8-4424-8b11-fef5767ed385)

**Comment by MoXiaoYan7612** [comment]
> @MoXiaoYan7612 还需要什么吗 ![image](https://private-user-images.githubusercontent.com/112249833/324152153-9665c33e-00c8-4424-8b11-fef5767ed385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1ODYxMzYsIm5iZiI6MTcxMzU4NTgzNiwicGF0aCI6Ii8xMTIyNDk4MzMvMzI0MTUyMTUzLTk2NjVjMzNlLTAwYzgtNDQyNC04YjExLWZlZjU3NjdlZDM4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwNDAzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTkzMDljYjNmNjEyYTIzZjcyYWVlMDI1YjNkN2E4N2E4YTgyYmRkYmVhZDdkNWI3Y2Q3Yzg3MzFkMmY2NzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MEmF1pq-Ob5e-OT_KlsEtp5vYObmgtFuYDE1AkDoMHo)

需要一个权限，玩家有权限才会触发这种重生[加入时可不可以空着，有需要在使用]

**Comment by xiantiao233** [comment]
我使用了group.xxxx
@MoXiaoYan7612

**Comment by MoXiaoYan7612** [comment]
> 我使用了group.xxxx

加入时的判断是每次加入时吗，如果是可不可以选用

**Comment by xiantiao233** [comment]
是触发事件之后，程序获取玩家的组，然后迭代插件设置的组进行判断(按照优先级)，最后传送

**Comment by xiantiao233** [comment]
![image](https://github.com/IdeaMC/Idea/assets/112249833/a2a0e281-c19d-4d79-ae63-4e2ab38418c4)

**Comment by MoXiaoYan7612** [comment]
没有了，感谢大佬

**Comment by xiantiao233** [comment]
@MoXiaoYan7612 
已完成，这个issues将被关闭，还有其他问题请前往[这里](https://github.com/IdeaMC/SpawnManager/issues)  
https://github.com/IdeaMC/SpawnManager

**Comment by MoXiaoYan7612** [comment]
> 已完成，这个问题将被关闭，还有其他问题请前往[这里](https://github.com/IdeaMC/SpawnManager/issues) https://github.com/IdeaMC/SpawnManager

感谢
